[package]
name = "embedded-hal-vcd"
version = "0.1.0"
authors = ["Niclas Hoyer <niclas@verbugt.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vcd = "0.6"
embedded-time = "0.10"
num-derive = "0.3"
num-traits = "0.2"
embedded-hal = "1.0.0-alpha.4"
fnv = "1.0"
